const tvShows = [
  "Peaky Blinders",
  "Breaking Bad",
  "The Walking Dead",
  "Fear The Walking Dead",
  "Batwoman",
  "Big Mouth",
  "Succession",
  "Arrow",
  "The Flash",
  "Flash",
  "Grey's Anatomy",
  "Friends",
  "Mr. Robot",
  "The Blacklist",
  "The Office",
  "Watchmen",
  "Better Call Saul",
  "Vikings",
  "Game of Thrones",
  "Orange is the New Black",
  "13 Reasons Why",
  "Stranger Things",
  "The Witcher",
  "Black Mirror",
  "Money Heist",
  "Shameless",
  "Gotham",
  "South Park",
  "Suits",
  "Brooklyn Nine-Nine",
  "The Big Bang Theory",
  "The Good Doctor",
  "Chernobyl",
  "The 100",
  "The One Hundred",
  "Westworld"
];

export default tvShows;
