const tvShows = [
  "13 Reasons Why",
  "24",
  "30 Rock",
  "Alias",
  "American Horror Story",
  "Archer",
  "Arrow",
  "Banshee",
  "Bates Motel",
  "Batwoman",
  "Better Call Saul",
  "Big Mouth",
  "Black Books",
  "Black Mirror",
  "Blue Bloods",
  "Boardwalk Empire",
  "Bored to Death",
  "Boss",
  "Breaking Bad",
  "Brooklyn Nine-Nine",
  "Buffy the Vampire Slayer",
  "CSI: Miami",
  "CSI: NY",
  "Californication",
  "Chapelle's Show",
  "Chernobyl",
  "Conan",
  "Dallas",
  "Deadwood",
  "Dexter",
  "Doctor Who",
  "Dragon Ball",
  "Dragon Ball Z",
  "Family Guy",
  "Fear The Walking Dead",
  "Firefly",
  "Flash",
  "Friends",
  "Full House",
  "Game of Thrones",
  "Gargoyles",
  "Gossip Girl",
  "Gotham",
  "Grey's Anatomy",
  "Grimm",
  "Hannibal",
  "Hell on Wheels",
  "Homeland",
  "House of Cards",
  "House of Lies",
  "I Love Lucy",
  "Jericho",
  "Lie to Me",
  "Life on Mars",
  "Louie",
  "Luther",
  "Mad Men",
  "Misfits",
  "Money Heist",
  "Monk",
  "Mr. Bean",
  "Mr. Robot",
  "Naruto",
  "Orange is the New Black",
  "Oz",
  "Peaky Blinders",
  "Prison Break",
  "Psych",
  "Revenge",
  "Rome",
  "Scandal",
  "Scooby Doo, Where Are You!",
  "Scrubs",
  "Sex and the City",
  "Shameless",
  "Sherlock",
  "Six Feet Under",
  "Smallville",
  "Sons of Anarchy",
  "South Park",
  "Southland",
  "Spider-Man",
  "Star Trek",
  "Stranger Things",
  "Succession",
  "Suits",
  "Suits",
  "Survivor",
  "Teen Wolf",
  "The 100",
  "The Adventures of Sherlock Holmes",
  "The Americans",
  "The Big Bang Theory",
  "The Blacklist",
  "The Flash",
  "The Good Doctor",
  "The IT Crowd",
  "The Killing",
  "The Mentalist",
  "The Office",
  "The One Hundred",
  "The Shield",
  "The Simpsons",
  "The Sopranos",
  "The Transformers",
  "The Vampire Diaries",
  "The Walking Dead",
  "The Wire",
  "The Witcher",
  "Top Gear",
  "True Blood",
  "Vikings",
  "Warehouse 13",
  "Watchmen",
  "Westworld",
  "White Collar",
  "Wonderfalls",
  "Young Justice",
  "iZombie"
];

export default tvShows;
